package com.school.fee.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import jakarta.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.time.LocalDate;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class FeePaymentScheduleRequest {
    @NotNull
    private Long studentId;

    @NotNull
    private String academicYear;

    @NotNull
    private BigDecimal totalAmount;

    @NotNull
    private LocalDate effectiveFrom;

    private String changeReason;

    private Integer numberOfInstallments;

    // Payment frequency like MONTHLY, QUARTERLY, etc.
    private String paymentFrequency;

    // Getters and setters are automatically generated by Lombok @Data annotation
    // But we need to ensure the methods called in service are available

    public LocalDate getEffectiveFrom() {
        return effectiveFrom;
    }

    public String getChangeReason() {
        return changeReason;
    }
}